energylab:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /tmp/energylab.duckdb # Try an absolute path in /tmp
      # Optional: Add extensions or other DuckDB settings here
      # extensions:
      #   - httpfs
      #   - parquet 