energylab:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ../energylab.duckdb # Path relative to profile file (..) from CWD (energylab/)
      # Optional: Add extensions or other DuckDB settings here
      # extensions:
      #   - httpfs
      #   - parquet 