energylab:
  target: dev
  outputs:
    dev:
      type: duckdb
      # path: /tmp/energylab.duckdb # Old path
      path: energylab.duckdb # Path relative to dbt_project.yml (root)
      # Optional: Add extensions or other DuckDB settings here
      # extensions:
      #   - httpfs
      #   - parquet 